# Generated by Django 4.2.6 on 2023-10-16 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Operator',
            fields=[
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('operator_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'operator',
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('booking_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('operator_id', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=100)),
                ('booking_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_rescheduled', models.BooleanField(default=False)),
                ('is_cancelled', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'booking',
                'indexes': [models.Index(fields=['booking_id'], name='booking_id_idx'), models.Index(fields=['operator_id'], name='operator_id_idx')],
            },
        ),
    ]
